# Generated by Django 4.2.30 on 2026-05-12 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lms_parents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KidsAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                ("avatar_id", models.CharField(default="1", max_length=10)),
                ("points", models.PositiveIntegerField(default=0)),
                ("level", models.PositiveIntegerField(default=1)),
                ("badges", models.JSONField(default=list)),
                ("favourite_color", models.CharField(default="green", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kids",
                        to="lms_parents.parentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KidsProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("lessons_completed", models.PositiveIntegerField(default=0)),
                ("stars", models.PositiveIntegerField(default=0)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "kid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="lms_kids.kidsaccount",
                    ),
                ),
            ],
            options={
                "unique_together": {("kid", "subject")},
            },
        ),
    ]
