# Generated by Django 4.2.30 on 2026-05-12 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "subjects",
                    models.TextField(blank=True, help_text="Comma-separated list of subjects"),
                ),
                ("hourly_rate", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("currency", models.CharField(default="UGX", max_length=10)),
                ("experience_years", models.PositiveIntegerField(default=0)),
                ("education", models.TextField(blank=True)),
                ("verified", models.BooleanField(default=False)),
                ("rating", models.FloatField(default=0.0)),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("availability", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
